// Code generated by "generr"; DO NOT EDIT.
package envconf

import (
	"fmt"

	"github.com/pkg/errors"
)

func IsEnvironmentVariableNotFound(err error) (bool, string) {
	err = errors.Cause(err)
	var envname string
	if e, ok := err.(environmentVariableNotFound); ok {
		envname = e.EnvironmentVariableNotFound()
		return true, envname
	}
	return false, envname
}

type EnvironmentVariableNotFound struct {
	Envname string
}

func (e *EnvironmentVariableNotFound) EnvironmentVariableNotFound() string {
	return e.Envname
}
func (e *EnvironmentVariableNotFound) Error() string {
	return fmt.Sprintf("environmentVariableNotFound Envname: %v", e.Envname)
}
