// Code generated by "generr"; DO NOT EDIT.
package envconf

import (
	"fmt"

	"github.com/pkg/errors"
)

func IsEnvironmentValueNotFound(err error) (bool, string) {
	err = errors.Cause(err)
	var envname string
	if e, ok := err.(environmentValueNotFound); ok {
		envname = e.EnvironmentValueNotFound()
		return true, envname
	}
	return false, envname
}

type EnvironmentValueNotFound struct {
	Envname string
}

func (e *EnvironmentValueNotFound) EnvironmentValueNotFound() string {
	return e.Envname
}
func (e *EnvironmentValueNotFound) Error() string {
	return fmt.Sprintf("environmentValueNotFound Envname: %v", e.Envname)
}
