// Code generated by "generr"; DO NOT EDIT.
package envconf

import (
	"fmt"

	"github.com/pkg/errors"
)

func IsNotPointerType(err error) bool {
	err = errors.Cause(err)
	if _, ok := err.(notPointerType); ok {
		return true
	}
	return false
}

type NotPointerType struct {
}

func (e *NotPointerType) NotPointerType() {
	return
}
func (e *NotPointerType) Error() string {
	return fmt.Sprint("notPointerType")
}
